# 阿里云帮助文档爬虫配置
base_url: "https://help.aliyun.com"

# 爬虫设置
crawler_settings:
  headless: true  # 是否无头模式
  wait_timeout: 10000  # 页面加载超时时间(毫秒)
  click_delay: 0.2  # 点击间隔(秒)
  crawl_delay: 0.5  # 文档爬取间隔(秒)
  max_depth: 10  # 最大展开深度
  debug_mode: false  # 是否启用详细调试输出

# 输出设置
output_settings:
  base_dir: "out"  # 输出目录
  include_content: false  # 是否包含文档内容(仅保存链接时设为false)
  recrawl_interval_hours: 24  # 文件刷新间隔（小时），24小时内不会重新爬取

# 阿里云产品配置
products:
  slb:
    name: "负载均衡"
    url: "https://help.aliyun.com/zh/slb/"
    description: "负载均衡 (SLB) 帮助文档"
  alb:
    name: "应用型负载均衡"
    url: "https://help.aliyun.com/zh/slb/application-load-balancer/"
    description: "应用型负载均衡 (ALB) 帮助文档"
  nlb:
    name: "网络型负载均衡"
    url: "https://help.aliyun.com/zh/slb/network-load-balancer/"
    description: "网络型负载均衡 (NLB) 帮助文档"
  gwlb:
    name: "网关型负载均衡"
    url: "https://help.aliyun.com/zh/slb/gateway-based-load-balancing-gwlb/"
    description: "网关型负载均衡 (GWLB) 帮助文档"
  clb:
    name: "传统型负载均衡"
    url: "https://help.aliyun.com/zh/slb/classic-load-balancer/"
    description: "传统型负载均衡 (CLB) 帮助文档"
  eip:
    name: "弹性公网IP"
    url: "https://help.aliyun.com/zh/eip/"
    description: "弹性公网IP (EIP) 帮助文档"
  anycasteip:
    name: "Anycast弹性公网IP"
    url: "https://help.aliyun.com/zh/anycast-eip/"
    description: "Anycast弹性公网IP帮助文档"
  cdt:
    name: "云数据传输CDT"
    url: "https://help.aliyun.com/zh/cdt/"
    description: "云数据传输CDT帮助文档"
  cbwp:
    name: "共享带宽"
    url: "https://help.aliyun.com/zh/internet-shared-bandwidth/"
    description: "共享带宽帮助文档"
  dtp:
    name: "共享流量包"
    url: "https://help.aliyun.com/zh/dtp/"
    description: "共享流量包帮助文档"
  vpc:
    name: "虚拟私有云"
    url: "https://help.aliyun.com/zh/vpc/"
    description: "虚拟私有云 (VPC) 帮助文档"
  nat:
    name: "NAT网关"
    url: "https://help.aliyun.com/zh/nat-gateway/"
    description: "NAT网关帮助文档"
  privatelink:
    name: "私网连接"
    url: "https://help.aliyun.com/zh/privatelink/"
    description: "私网连接 (PrivateLink) 帮助文档"
  nis:
    name: "网络智能服务"
    url: "https://help.aliyun.com/zh/nis/"
    description: "网络智能服务 (NIS) 帮助文档"
  ipv6gateway:
    name: "IPv6网关"
    url: "https://help.aliyun.com/zh/ipv6-gateway/"
    description: "IPv6网关帮助文档"
  cen:
    name: "云企业网"
    url: "https://help.aliyun.com/zh/cen/"
    description: "云企业网 (CEN) 帮助文档"
  ga:
    name: "全球加速"
    url: "https://help.aliyun.com/zh/ga/"
    description: "全球加速 (GA) 帮助文档"
  vpn:
    name: "VPN网关"
    url: "https://help.aliyun.com/zh/vpn/"
    description: "VPN网关帮助文档"
  ipsecvpn:
    name: "IPsec-VPN连接"
    url: "https://help.aliyun.com/zh/vpn/sub-product-ipsec-vpn"
    description: "IPsec-VPN连接帮助文档"
  sslvpn:
    name: "SSL-VPN连接"
    url: "https://help.aliyun.com/zh/vpn/sub-product-ssl-vpn"
    description: "SSL-VPN连接帮助文档"
  ec:
    name: "高速通道"
    url: "https://help.aliyun.com/zh/express-connect/"
    description: "高速通道 (Express Connect) 帮助文档"

# 内容提取器配置
content_extractor:
  type: "readability" # simple or readability
  settings:
    min_content_length: 100
    # for simple extractor
    content_selectors:
      - ".content-body"
      - ".doc-content"
      - ".article-content"
      - "main" 