# 火山引擎帮助文档爬虫配置
base_url: "https://www.volcengine.com"

# 爬虫设置
crawler_settings:
  headless: true
  wait_timeout: 20000
  click_delay: 0.2
  crawl_delay: 0.5
  debug_mode: false

# 输出设置
output_settings:
  base_dir: "out"
  include_content: false
  recrawl_interval_hours: 24

# 火山引擎产品配置
products:
  network_overview:
    name: "网络介绍"
    url: "https://www.volcengine.com/docs/6968"
    description: "火山引擎网络产品介绍"
  vpc:
    name: "私有网络"
    url: "https://www.volcengine.com/docs/6401"
    description: "私有网络 (VPC) 帮助文档"
  eip:
    name: "公网IP"
    url: "https://www.volcengine.com/docs/6402"
    description: "公网IP (EIP) 帮助文档"
  shared_bandwidth_package:
    name: "共享带宽包"
    url: "https://www.volcengine.com/docs/6623"
    description: "共享带宽包帮助文档"
  nat_gateway:
    name: "NAT网关"
    url: "https://www.volcengine.com/docs/6404"
    description: "NAT网关帮助文档"
  ipv6_gateway:
    name: "IPv6网关"
    url: "https://www.volcengine.com/docs/6896"
    description: "IPv6网关帮助文档"
  cen:
    name: "云企业网"
    url: "https://www.volcengine.com/docs/6405"
    description: "云企业网 (CEN) 帮助文档"
  transit_router:
    name: "中转路由器"
    url: "https://www.volcengine.com/docs/6979"
    description: "中转路由器 (TR) 帮助文档"
  clb:
    name: "负载均衡"
    url: "https://www.volcengine.com/docs/6406"
    description: "负载均衡 (CLB) 帮助文档"
  direct_connect:
    name: "专线连接"
    url: "https://www.volcengine.com/docs/6407"
    description: "专线连接帮助文档"
  vpn_connection:
    name: "VPN连接"
    url: "https://www.volcengine.com/docs/6455"
    description: "VPN连接帮助文档"
  alb:
    name: "应用型负载均衡"
    url: "https://www.volcengine.com/docs/6767"
    description: "应用型负载均衡 (ALB) 帮助文档"
  private_link:
    name: "私网连接"
    url: "https://www.volcengine.com/docs/6980"
    description: "私网连接帮助文档"
  nic:
    name: "网络智能中心"
    url: "https://www.volcengine.com/docs/83782"
    description: "网络智能中心帮助文档"
  cloud_connector:
    name: "云连接器"
    url: "https://www.volcengine.com/docs/83812"
    description: "云连接器帮助文档"
  shared_traffic_package:
    name: "共享流量包"
    url: "https://www.volcengine.com/docs/84435"
    description: "共享流量包帮助文档"

# 内容提取器配置
content_extractor:
  type: "readability" # simple or readability
  settings:
    min_content_length: 100
    # for simple extractor
    content_selectors:
      - ".markdown-body"
      - '[data-testid="page-content"]'
      - "article"
      - "main" 